config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :new, :index, :destroy]
  resource :search, only: [:create, :show, :edit, :create]

  namespace :admin do
    resources :trains do
     resources :carriages, shallow: true
    end

    resources :routes
    resources :carriages
    resources :tickets

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end  
  end  

  get 'welcome/index'

  root 'searches#show'

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to admin_route_path(@route), notice: 'Route created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route, notice: 'Route update'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_train
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, @route] do |f| %>
    <%= render 'common/errors', resource: @route %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :railway_station_ids, "Station list" %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
    </div>

    <div class="actions">
      <%= f.submit "#{ @route.new_record? ? 'Create' : 'Update' }" %>
    </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Show', [:admin, route] %></td>
  <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
  <td><%= link_to 'Destroy', [:admin, route], method: :delete, data: { confirm: 'Are you sure?'} %></td>
</tr>

app/views/admin/routes/_stations.html.erb
<% if @route.railway_stations.empty? %>
  <p>The route no stations</p>
<% else %>
  <table>
    <thead>
      <tr>
        <td weight="100px">Station name:</td>
        <td>Position</td>
      </tr>
    </thead>
    <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
        <tr>
          <td><%= station.title %></td>
          <td>
            <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
              <%= number_field_tag :position, station.position_in(@route) %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag "Edit" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %> 

app/views/admin/routes/_train.html.erb
<% if @route.trains.empty? %>
  <p>There is no trains on the route</p>
<% else %>
  <p> Trains on the route:</p>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
<% end %> 

app/views/admin/routes/edit.html.erb
<h1>Edit route</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1>Listing Routes</h1>

<table>
  <thead>
  <tr>
    <th>Route number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @routes %>   
  </tbody>

</table>

<br>

<%= link_to 'Add route', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @route.name %>
<p>

<%= render 'stations' %>

<%= render 'train' %>

<%= link_to 'Edit', edit_admin_route_path(@route) %>
<%= link_to 'Back', admin_routes_path %>