config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :new, :index, :destroy]
  resource :search, only: [:create, :show, :edit, :create]

  namespace :admin do
    resources :trains do
     resources :carriages, shallow: true
    end

    resources :routes
    resources :carriages
    resources :tickets

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end  
  end  

  get 'welcome/index'

  root 'searches#show'

end

app/models/carriage.rb
class Carriage < ActiveRecord::Base
  TYPES =  {coupe: 'CoupeCarriage',
            economy: 'EconomyCarriage',
            sitting: 'SittingCarriage',
            comfortable: 'ComfortableCarriage'}

  validates :number, uniqueness: { scope: :train_id }
  before_validation :set_number

  belongs_to :train

  # scope :coupe,             -> { where(type: 'CoupeCarriage') }
  # scope :economy,           -> { where(type: 'EconomyCarriage') }
  # scope :sitting,           -> { where(type: 'SittingCarriage') }
  # scope :comfortable,       -> { where(type: 'ComfortableCarriage') }

  TYPES.each_pair do |type_name, type|
    scope type_name, -> { where(type: type) }
  end

  # scope :total_top,         -> { sum(:top_seats) }
  # scope :total_bottom,      -> { sum(:bottom_seats) }
  # scope :total_sitting,     -> { sum(:sitting_seats) }
  # scope :total_side_top,    -> { sum(:side_top_seats) }
  # scope :total_side_bottom, -> { sum(:side_bottom_seats) }

  scope :ordered, ->(order) { order(number: order ? 'asc' : 'desc') }

  private

  def set_number
    self.number = train.carriages.size + 1
  end

  def self.types
    TYPES.values
  end

  def self.total_seats(type)
    sum(type)
  end
end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @carriages = Carriage.all
  end

  def show
  end

  def new
    @carriage = Carriage.new
  end

  def create
    @carriage = @train.carriages.new(carriage_params)
    if @carriage.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @carriage.update(carriage_params)
      redirect_to admin_carriage_path(@carriage), notice: 'Carriage update'
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy
    redirect_to admin_carriages_path
  end

  private

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def set_train
    @train = Train.find(params[:train_id])
  end  

  def carriage_params
    params.require(:carriage).permit(:number,
                                     :id, 
                                     :type,
                                     :train_id,
                                     :top_seats,
                                     :bottom_seats,
                                     :side_top_seats,
                                     :side_bottom_seats,
                                     :sitting_seats)
  end
end

app/views/admin/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.number %></td>
  <td><%= carriage.type %></td>
  <td><%= link_to 'Show', carriage_path(carriage) %></td>
  <td><%= link_to 'Edit', edit_carriage_path(carriage) %></td>
  <td><%= link_to 'Delete', carriage_path(carriage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/carriages/_comfortablecarriage.html.erb
<p>
  <strong>Comfortable carriage</strong>
  <%= @carriage.number %><br>
  <strong>Bottom seats count:</strong>
  <%= @carriage.bottom_seats %>
</p>

app/views/admin/carriages/_coupecarriage.html.erb
<p>
  <strong>Coupe carriage</strong>
  № <%= @carriage.number %><br>
  <strong>Top seats count:</strong>
  <%= @carriage.top_seats %><br>
  <strong>Bottom seats count:</strong>
  <%= @carriage.bottom_seats %>
</p>

app/views/admin/carriages/_economycarriage.html.erb
<p>
  <strong>Economy carriage</strong>
  № <%= @carriage.number %><br>
  <strong>Top seats count:</strong>
  <%= @carriage.top_seats %><br>
  <strong>Bottom seats count:</strong>
  <%= @carriage.bottom_seats %><br>
  <strong>Side top seats count:</strong>
  <%= @carriage.side_top_seats %><br>
  <strong>Side bottom seats count:</strong>
  <%= @carriage.side_bottom_seats %>
</p>

app/views/admin/carriages/_form.html.erb
<%= form_for [:admin, @train, carriage.becomes(Carriage)] do |f| %>


  <div class="field hidden" id="top">
    <%= f.label :top_seats, 'Top seats' %>
    <%= f.text_field :top_seats %>
  </div>

  <div class="field hidden" id="bottom">
    <%= f.label :bottom_seats, 'Bottom seats' %>
    <%= f.text_field :bottom_seats %>
  </div>

  <div class="field hidden" id="side_top">
    <%= f.label :side_top_seats, 'Side top seats' %>
    <%= f.text_field :side_top_seats %>
  </div>

  <div class="field hidden" id="side_bottom">
    <%= f.label :side_bottom_seats, 'Side bottom seats' %>
    <%= f.text_field :side_bottom_seats %>
  </div>

  <div class="field hidden" id="sitting">
    <%= f.label :sitting_seats, 'Sitting seats' %>
    <%= f.text_field :sitting_seats %>
  </div>

  <div class="field" id="field_carriage_type">
    <%= f.label :type, 'Type of carriage' %>
    <%= f.select :type, Carriage.types %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @carriage.new_record? ? 'Create' : 'Edit' }" %>
  </div>
<% end %>

app/views/admin/carriages/_sittingcarriage.html.erb
<p>
  <strong>Sitting carriage</strong>
  № <%= @carriage.number %><br>
  <strong>Sitting seats count:</strong>
  <%= @carriage.sitting_seats %>
</p>

app/views/admin/carriages/edit.html.erb
<h1>Edit carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Back', [:admin, @carriage.train] %>

app/views/admin/carriages/index.html.erb
<h1>Listing Carriages</h1>

<table>
  <thead>
  <tr>
    <th>Carriage type</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render partial: "carriage", collection: @carriages %>
  </tbody>

</table>

<br>

<%= link_to 'Add carriage', new_carriage_path %>

app/views/admin/carriages/new.html.erb
<h1>New carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Back', [:admin, @train] %>

app/views/admin/carriages/show.html.erb
<p>
  <strong>These carriage:</strong>
    <%= render @carriage.type.downcase, carriage: @carriage %>
</p>

<%= link_to 'Edit', edit_admin_carriage_path(@carriage) %> |
<%= link_to 'Back', [:admin, @carriage.train] %>