config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :new, :index, :destroy]
  resource :search, only: [:create, :show, :edit, :create]

  namespace :admin do
    resources :trains do
     resources :carriages, shallow: true
    end

    resources :routes
    resources :carriages
    resources :tickets

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end  
  end  

  get 'welcome/index'

  root 'searches#show'

end

app/models/search.rb
class Search
  include ActiveModel::Model

  attr_accessor :start_station, :end_station
  attr_accessor :start_station_id, :end_station_id
  attr_accessor :result

  def self.do(params = {})
    search = Search.new(
      start_station_id: params[:start_station_id],
      end_station_id: params[:end_station_id],
    )
    search.start_station = RailwayStation.find(params[:start_station_id])
    search.end_station = RailwayStation.find(params[:end_station_id])
    search.result = search.trains_by_route_station(search.start_station) & search.trains_by_route_station(search.end_station)
    search
  end

  def trains_by_route_station(station)
    Train.includes(route: :railway_stations).where(railway_stations: {id: station.id})
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.new
  end

  def create
    @search = Search.do(search_params)
    render :show
  end

  private

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search, url: { action: 'show' } do |f| %>
  <div class="row">  
    <div class="col-md-4">
      <div class="field">
        <%= f.label :start_station_id, 'Start station' %>
        <%= f.collection_select :start_station_id, RailwayStation.all, :id, :title %>
      </div>
    </div>    
    <div class="col-md-4">
      <div class="field">
        <%= f.label :end_station_id, 'End station' %>
        <%= f.collection_select :end_station_id, RailwayStation.all, :id, :title %>
      </div>
    </div>
    <div class="col-md-4"> 
      <div class="actions">
        <%= f.submit 'Search' %>
      </div>  
    </div> 
  </div>   

<% end %>

app/views/searches/_result.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Train</th>
      <th>Route</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @search.result.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= train.route.name %></td>
        <td><%= @search.start_station.time(train.route, :departure) %></td>
        <td><%= @search.end_station.time(train.route, :arrival) %></td>
        <td>
            <% if user_signed_in? && current_user.admin? %>
              <%= link_to 'Buy ticket', new_admin_ticket_path(ticket: { train_id: train.id, start_station_id: @search.start_station.id, end_station_id: @search.end_station.id }) %>
          <% else %>
          <%= link_to 'Buy ticket', new_ticket_path(ticket: { train_id: train.id, start_station_id: @search.start_station.id, end_station_id: @search.end_station.id }) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/show.html.erb
<h1>Search tickets</h1>

<div>
  <%= render 'form' %>
</div>

<div>
  <% if @search.result.present? %>
    <h1>Search results:</h1>
    <%= render 'result' %>
  <% end %>
</div>