config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:create, :show, :new, :index, :destroy]
  resource :search, only: [:create, :show, :edit, :create]

  namespace :admin do
    resources :trains do
     resources :carriages, shallow: true
    end

    resources :routes
    resources :carriages
    resources :tickets

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end  
  end  

  get 'welcome/index'

  root 'searches#show'

end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation' #, foreign_key: :current_station_id
  has_many :tickets
  has_many :carriages

  before_create :set_number

  private

  def set_number
    self.number = Train.all.count + 1
  end

  def count_seats(type, seats)
    carriages.where(type: type).sum(seats)
  end

  def count_carriages(type)
    carriages.where(type: type).count
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)
      if @train.save
        redirect_to [:admin, @train], notice: 'Train was successfully created.'
      else
        render :new
      end
  end

  def update
    if @train.update(train_params)
      redirect_to [:admin, @train], notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: 'Train was successfully destroyed.'
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :queue, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |f| %>
      <%= render 'common/errors', resource: @train %>

<% if @train.new_record? == false %>
    <div class="field">
      <%= f.label :number %><br>
      <%= f.number_field :number %>
    </div>
<% end %>

  <div class="field">
    <%= f.label :route, "Route" %>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: @train.new_record? ? 'Создать' : 'Изменить' ) %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to t('common.show'), [:admin, train] %></td>
  <td><%= link_to t('common.edit'), edit_admin_train_path(train) %></td>
  <td><%= link_to t('common.destroy'), [:admin, train], method: :delete, data: { confirm: "#{t('common.are_you_sure')}" } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.show'), [:admin, @train] %> |
<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1><%= t('.list') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.number') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to t('common.create_new_train'), new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong><%= t('.number') %></strong>
  <%= @train.number %>
</p>
<p>
  <strong><%= t('.current_station') %></strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Not specified
  <% end %>
</p>

<p>
  <strong><%= t('.route') %></strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Not specified
  <% end %>
</p>

<p>
  <strong><%= t('.carriages') %></strong>
  <ul>
    <% @train.carriages.each do |car| %>
      <li><%= link_to "#{t('.carriage_n')} #{car.number}", [:admin, car.becomes(Carriage)] %></li>
    <% end %>
  </ul>
 </p>

 <p>
    <%= link_to t('common.add_carriage'), new_admin_train_carriage_path(@train) %>
 </p>



<%= link_to t('common.edit'), edit_admin_train_path(@train) %> |
<%= link_to t('common.back'), admin_trains_path %>